---
name: Deploy AWS Infrastructure

"on":
  push:
    branches:
      - main

jobs:
  deploy-eventbridge:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      REGION: ${{ secrets.AWS_REGION }}
      ROLE_ARN: ${{ secrets.ROLE_ARN }}
      BUCKET_NAME: ${{ secrets.GLUE_BUCKET }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_WEB_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Who am I?
        run: aws sts get-caller-identity

      - name: Install Deployment Dependencies
        run: |
          pip install boto3

      - name: Deploy EventBridge Rule
        run: |
          python scripts/deploy_eventbridge.py \
            ${{ secrets.AWS_REGION }} ${{ secrets.GLUE_BUCKET }}
